# Generated by Django 3.0.7 on 2021-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=254)),
                ('address', models.TextField(max_length=254)),
                ('Birthdate', models.TextField(max_length=254)),
                ('Birthmonth', models.TextField(max_length=254)),
                ('Birthyear', models.TextField(max_length=254)),
                ('Hobbies', models.TextField(max_length=254)),
                ('Diagnosis', models.TextField(max_length=254)),
                ('Work', models.TextField(max_length=254)),
                ('Diet', models.TextField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=191)),
                ('answer', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=254)),
                ('lastname', models.TextField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Birthdate', models.TextField(max_length=254)),
                ('City', models.TextField(max_length=254)),
                ('imageuser', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/')),
            ],
        ),
    ]
