# Generated by Django 3.0.7 on 2021-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Mobile',
            field=models.CharField(max_length=100),
        ),
    ]
